spring:
  datasource:
    url: jdbc:mysql://${RDS_ENDPOINT:localhost}:3306/order_project?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false&rewriteBatchedStatements=true
    username: order_project_user
    password: ${RDS_PASSWORD:password1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 32
  # // TODO: Named Lock ? ?? ?? ??? ?????
  #    hikari:
  #      maximum-pool-size: 64
  jpa:
    defer-datasource-initialization: true
    hibernate:
#      ddl-auto: create
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    #        session_factory:
    #          statement_inspector: ding.co.backendportfolio.chapter5.config.QueryCountInspector
    database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: redis
      port: 6379
  sql:
    init:
      mode: never

logging:
  level:
    org.springframework: info
# TODO: BulkInsert ???? - ?? ??? ?????
#    com.mysql.cj: trace

#jwt:
#  secret: your-256-bit-secret-your-256-bit-secret-your-256-bit-secret-your-256-bit-secret
#  token-validity-in-seconds: 86400  # 24??

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,info,prometheus"
  endpoint:
    health:
      show-details: always  # ??? ?? ?? ??

server:
  tomcat:
    connection-timeout: 120000      # 120?
  servlet:
    session:
      timeout: 120s                # ?? ????
    encoding:
      charset: UTF-8
      enabled: true
      force: true
