spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/data/testdb
    url: jdbc:h2:file:~/data/testdb
#    url: jdbc:h2:mem:testdb  # 인메모리 H2 DB 사용
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true

  sql:
    init:
      mode: always