### 주문 상세 조회
GET http://localhost:8080/api/orders/1

### 주문 페이지 조회
GET http://localhost:8080/api/orders

### 주문 날짜 범위로 검색 (2025-08-01 ~ 2025-08-15)
GET http://localhost:8080/api/orders?orderDateFrom=2025-08-01&orderDateTo=2025-08-15

### 배송 상태와 최소 주문 금액으로 검색 (배송 완료, 3만원 이상)
GET http://localhost:8080/api/orders?deliveryStatus=ORDER&minPrice=30000

### 가격 높은 순 (정렬)
GET http://localhost:8080/api/orders?sortBy=priceDesc

### 가격 낮은 순 (정렬)
GET http://localhost:8080/api/orders?sortBy=priceAsc

### 페이징 처리
GET http://localhost:8080/api/orders?page=2&size=5

### 복합 조건 활용 (memberId 존재)
GET http://localhost:8080/api/orders?memberId=13415&deliveryStatus=ORDER&sortBy=priceAsc&orderDateFrom=2025-08-01&orderDateTo=2025-08-15&minPrice=30000

### 복합 조건 활용
GET http://localhost:8080/api/orders?deliveryStatus=ORDER&sortBy=priceAsc&orderDateFrom=2025-08-01&orderDateTo=2025-08-15&minPrice=30000

###
# @connection-timeout 5 m
GET http://localhost:8080/api/orders/statistics/member-stats

###
# @connection-timeout 5 m
GET http://localhost:8080/api/orders/stats?page=100&minAmount=30000

###
# @connection-timeout 5 m
GET http://localhost:8080/api/orders/statistics/member-stats?page=0&size=1&minAmount=10000

###
# @connection-timeout 5 m
GET http://localhost:8080/api/orders/statistics/stats/v1?page=100&minAmount=30000

###
GET http://localhost:8080/api/orders/v2?memberId=13415&minAmount=30000&year=2025&keyword=Product

### 주문 생성 요청 (김유신 회원)
POST http://localhost:8080/api/orders?memberId=3
Content-Type: application/json
#Authorization: Bearer <USER_ACCESS_TOKEN>

{
  "totalAmount": 230000,
  "orderName": "키보드 외 1건",
  "productValues": [
    {
      "productId": 3,
      "price": 80000,
      "quantity": 2
    },
    {
      "productId": 5,
      "price": 70000,
      "quantity": 1
    }
  ]
}